"""ORM models. Importing this package registers every table on ``Base.metadata``."""

from optiedt.models.academic import ActivityType, CalendarEvent, Course, Instructor, Programme
from optiedt.models.audit import AuditEvent
from optiedt.models.identity import (
    CalendarFeedToken,
    LoginThrottle,
    RoleAssignment,
    StudentMembership,
    User,
    UserSession,
)
from optiedt.models.idempotency import IdempotencyRecord
from optiedt.models.imports import ImportBatch
from optiedt.models.organization import (
    Building,
    Campus,
    CampusTravelTime,
    Department,
    Institution,
    Room,
    RoomFeature,
    RoomType,
    room_feature_links,
)
from optiedt.models.scheduling import (
    OccurrenceException,
    ProblemSnapshot,
    Publication,
    PublicationAssignment,
    Scenario,
    Solution,
    SolutionAssignment,
    SolutionChange,
    SolverRun,
    SolverRunEvent,
    WorkerHeartbeat,
)
from optiedt.models.term import (
    Activity,
    ActivityRoom,
    AvailabilityGrid,
    ConstraintRule,
    FixedPlacement,
    ObjectiveProfile,
    Period,
    SlotSetting,
    StudentGroup,
    Term,
    TimingVariant,
    TimingVariantPeriod,
    activity_features,
    activity_groups,
    activity_instructors,
)

__all__ = [
    "Activity",
    "ActivityRoom",
    "ActivityType",
    "AuditEvent",
    "AvailabilityGrid",
    "Building",
    "CalendarEvent",
    "CalendarFeedToken",
    "Campus",
    "CampusTravelTime",
    "ConstraintRule",
    "Course",
    "Department",
    "FixedPlacement",
    "IdempotencyRecord",
    "ImportBatch",
    "Institution",
    "Instructor",
    "LoginThrottle",
    "ObjectiveProfile",
    "OccurrenceException",
    "Period",
    "ProblemSnapshot",
    "Programme",
    "Publication",
    "PublicationAssignment",
    "RoleAssignment",
    "Room",
    "RoomFeature",
    "RoomType",
    "Scenario",
    "SlotSetting",
    "Solution",
    "SolutionAssignment",
    "SolutionChange",
    "SolverRun",
    "SolverRunEvent",
    "StudentGroup",
    "StudentMembership",
    "Term",
    "TimingVariant",
    "TimingVariantPeriod",
    "User",
    "UserSession",
    "WorkerHeartbeat",
    "activity_features",
    "activity_groups",
    "activity_instructors",
    "room_feature_links",
]
