"""Record published timetables

Revision ID: 04462f0db630
Revises: 4553e7a29780
Create Date: 2026-08-04 19:25:34.061771

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "04462f0db630"
down_revision: str | None = "4553e7a29780"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "publications",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("candidate_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_by", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
            name=op.f("fk_publications_candidate_id_candidates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publications")),
    )
    op.create_index(
        op.f("ix_publications_candidate_id"), "publications", ["candidate_id"], unique=False
    )
    op.create_index(
        op.f("ix_publications_published_at"), "publications", ["published_at"], unique=False
    )
    op.create_index(op.f("ix_publications_run_id"), "publications", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_publications_run_id"), table_name="publications")
    op.drop_index(op.f("ix_publications_published_at"), table_name="publications")
    op.drop_index(op.f("ix_publications_candidate_id"), table_name="publications")
    op.drop_table("publications")
    # ### end Alembic commands ###
