"""Record every run with its data, seed, weights and results

Revision ID: 5d1497398fab
Revises:
Create Date: 2026-08-04 14:23:36.818736

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5d1497398fab"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "availability_declarations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("teacher", sa.String(length=64), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("semester", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_availability_declarations")),
        sa.UniqueConstraint(
            "teacher", "slot", "semester", name=op.f("uq_availability_declarations_teacher")
        ),
    )
    op.create_index(
        op.f("ix_availability_declarations_teacher"),
        "availability_declarations",
        ["teacher"],
        unique=False,
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("deterministic_budget", sa.Float(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("duplicates_removed", sa.JSON(), nullable=False),
        sa.Column("deterministic_time_used", sa.Float(), nullable=False),
        sa.Column("wall_clock_seconds", sa.Float(), nullable=False),
        sa.Column("error", sa.String(length=2048), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    op.create_index(op.f("ix_runs_created_at"), "runs", ["created_at"], unique=False)
    op.create_table(
        "candidates",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("rank_order", sa.Integer(), nullable=False),
        sa.Column("profile_name", sa.String(length=32), nullable=False),
        sa.Column("cost", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_candidates_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidates")),
    )
    op.create_index(op.f("ix_candidates_run_id"), "candidates", ["run_id"], unique=False)
    op.create_table(
        "run_checks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("resource", sa.String(length=128), nullable=True),
        sa.Column("missing_quantity", sa.Float(), nullable=True),
        sa.Column("detail", sa.String(length=4096), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_checks_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_checks")),
        sa.UniqueConstraint("run_id", "name", name=op.f("uq_run_checks_run_id")),
    )
    op.create_index(op.f("ix_run_checks_run_id"), "run_checks", ["run_id"], unique=False)
    op.create_table(
        "run_diagnoses",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("conflicting_codes", sa.JSON(), nullable=False),
        sa.Column("is_minimal", sa.Boolean(), nullable=False),
        sa.Column("is_conclusive", sa.Boolean(), nullable=False),
        sa.Column("detail", sa.String(length=4096), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_diagnoses_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_run_diagnoses")),
    )
    op.create_table(
        "run_weights",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("criterion", sa.String(length=8), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_weights_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_weights")),
        sa.UniqueConstraint("run_id", "criterion", name=op.f("uq_run_weights_run_id")),
    )
    op.create_index(op.f("ix_run_weights_run_id"), "run_weights", ["run_id"], unique=False)
    op.create_table(
        "placements",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("candidate_id", sa.String(length=64), nullable=False),
        sa.Column("session", sa.String(length=64), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column("room", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
            name=op.f("fk_placements_candidate_id_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_placements")),
        sa.UniqueConstraint("candidate_id", "session", name=op.f("uq_placements_candidate_id")),
    )
    op.create_index(
        op.f("ix_placements_candidate_id"), "placements", ["candidate_id"], unique=False
    )
    op.create_table(
        "sub_scores",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("candidate_id", sa.String(length=64), nullable=False),
        sa.Column("criterion", sa.String(length=8), nullable=False),
        sa.Column("raw_value", sa.Float(), nullable=False),
        sa.Column("normalised", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
            name=op.f("fk_sub_scores_candidate_id_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sub_scores")),
        sa.UniqueConstraint("candidate_id", "criterion", name=op.f("uq_sub_scores_candidate_id")),
    )
    op.create_index(
        op.f("ix_sub_scores_candidate_id"), "sub_scores", ["candidate_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sub_scores_candidate_id"), table_name="sub_scores")
    op.drop_table("sub_scores")
    op.drop_index(op.f("ix_placements_candidate_id"), table_name="placements")
    op.drop_table("placements")
    op.drop_index(op.f("ix_run_weights_run_id"), table_name="run_weights")
    op.drop_table("run_weights")
    op.drop_table("run_diagnoses")
    op.drop_index(op.f("ix_run_checks_run_id"), table_name="run_checks")
    op.drop_table("run_checks")
    op.drop_index(op.f("ix_candidates_run_id"), table_name="candidates")
    op.drop_table("candidates")
    op.drop_index(op.f("ix_runs_created_at"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(
        op.f("ix_availability_declarations_teacher"), table_name="availability_declarations"
    )
    op.drop_table("availability_declarations")
    # ### end Alembic commands ###
