"""Store the administrator's calendar and a student's group

Revision ID: e62aaacddedf
Revises: 5bb01757f0cc
Create Date: 2026-08-11 00:45:58.433810

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e62aaacddedf"
down_revision: str | None = "5bb01757f0cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendar_overrides",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("slot_open", sa.JSON(), nullable=False),
        sa.Column("holidays", sa.JSON(), nullable=True),
        sa.Column("shortened_day", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_overrides")),
    )
    op.add_column("users", sa.Column("group", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_users_group"), "users", ["group"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_group"), table_name="users")
    op.drop_column("users", "group")
    op.drop_table("calendar_overrides")
    # ### end Alembic commands ###
